# Generated by Django 4.0.4 on 2022-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='component_start_time',
        ),
        migrations.AddField(
            model_name='components',
            name='types',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
