# Generated by Django 4.0.4 on 2022-05-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_rename_business_template_business_and_more'),
        ('super_template', '0002_remove_components_component_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlays',
            name='logos',
        ),
        migrations.RemoveField(
            model_name='overlays',
            name='text_element',
        ),
        migrations.AlterField(
            model_name='supertemplate',
            name='background_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.backgroundscore'),
        ),
        migrations.AlterField(
            model_name='supertemplate',
            name='overlays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.overlays'),
        ),
        migrations.DeleteModel(
            name='BackgroundScore',
        ),
        migrations.DeleteModel(
            name='Logos',
        ),
        migrations.DeleteModel(
            name='Overlays',
        ),
        migrations.DeleteModel(
            name='TextElement',
        ),
    ]
