# Generated by Django 4.0.4 on 2022-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_inflectiontime_data_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflectiontime',
            name='data_field',
            field=models.FloatField(),
        ),
    ]
