# Generated by Django 4.0.4 on 2022-05-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logos', models.ManyToManyField(to='template.logos')),
                ('text_element', models.ManyToManyField(to='template.textelement')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=30)),
                ('watemark', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('template_url', models.FileField(null=True, upload_to='media')),
                ('background_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.backgroundscore')),
                ('components', models.ManyToManyField(to='template.components')),
                ('overlays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.overlays')),
            ],
        ),
    ]
