# Generated by Django 4.0.4 on 2022-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_overlays_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='Business',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='watemark',
            new_name='watermark',
        ),
        migrations.AlterField(
            model_name='textelement',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
